the_click_cms_admin_homepage:
    pattern:  /hello/{name}
    defaults: { _controller: TheClickCmsAdminBundle:Default:index }


hacerLogin:
    pattern:  /admin/hacerLogin
    defaults: { _controller: TheClickCmsAdminBundle:Default:hacerLogin }


uploadActualizaciones:
    pattern:  /admin/uploadActualizaciones
    defaults: { _controller:  TheClickCmsAdminBundle:Default:uploadActualizaciones }


login:
    pattern:  /admin/
    defaults: { _controller: TheClickCmsAdminBundle:Default:login }

vistauploadArchivo:
    path:      /admin/vistauploadArchivo
    defaults:  { _controller: TheClickCmsAdminBundle:Default:vistauploadArchivo }

guardarEmpresa:
    pattern:  /admin/guardarEmpresa
    defaults: { _controller: TheClickCmsAdminBundle:Default:guardarEmpresa }


vistaAgregarEmpresa:
   pattern:  /admin/vistaAgregarEmpresa
   defaults: { _controller: TheClickCmsAdminBundle:Default:vistaAgregarEmpresa  }

listarEmpresas:
    pattern: /admin/listarEmpresas
    defaults: {_controller: TheClickCmsAdminBundle:Default:listarEmpresas }

vistaEditarEmpresa:
    pattern: /admin/vistaEditarEmpresa/{id}
    defaults: {_controller: TheClickCmsAdminBundle:Default:vistaEditarEmpresa}

guardarEditarEmpresa:
    pattern: /admin/guardarEditarEmpresa
    defaults: {_controller: TheClickCmsAdminBundle:Default:guardarEditarEmpresa}

eliminarEmpresa:
    pattern: /admin/eliminarEmpresa/
    defaults: {_controller: TheClickCmsAdminBundle:Default:eliminarEmpresa}

logout:
    pattern:  /admin/
    defaults: { _controller: TheClickCmsAdminBundle:Default:logout  }

principal:
    pattern:  /admin/principal
    defaults: { _controller: TheClickCmsAdminBundle:Default:principal }

vistaFormularioUsuario:
    pattern: /admin/vistaFormularioUsuario
    defaults: {_controller: TheClickCmsAdminBundle:Default:vistaFormularioUsuario }

guardarUsuario:
    pattern: /admin/guardarUsuario
    defaults: {_controller: TheClickCmsAdminBundle:Default:guardarUsuario}

listarUsuarios:
    pattern: /admin/listarUsuarios
    defaults: {_controller: TheClickCmsAdminBundle:Default:listarUsuarios}

vistaEditarUsuario:
    pattern: /admin/vistaEditarUsuario/{id}
    defaults: {_controller: TheClickCmsAdminBundle:Default:vistaEditarUsuario}

guardarFormularioEditarUsuario:
    pattern: /admin/guardarFormularioEditarUsuario
    defaults: {_controller: TheClickCmsAdminBundle:Default:guardarFormularioEditarUsuario}

eliminarUsuario:
    pattern: /admin/eliminarUsuario/
    defaults: {_controller: TheClickCmsAdminBundle:Default:eliminarUsuario}

vistaAgregarActualizacion:
    pattern: /admin/vistaAgregarActualizacion
    defaults: {_controller: TheClickCmsAdminBundle:Default:vistaAgregarActualizacion}

guardarActualizacion:
    pattern: /admin/guardarActualizacion
    defaults: {_controller: TheClickCmsAdminBundle:Default:guardarActualizacion}

listarActualizacion:
    pattern: /admin/listarActualizacion
    defaults: {_controller: TheClickCmsAdminBundle:Default:listarActualizacion}

vistaEditarActualizacion:
    pattern: /admin/vistaEditarActualizacion/{id}
    defaults: {_controller: TheClickCmsAdminBundle:Default:vistaEditarActualizacion}

guardarEditarActualizacion:
    pattern: /admin/guardarEditarActualizacion
    defaults: {_controller: TheClickCmsAdminBundle:Default:guardarEditarActualizacion}

eliminarActualizacion:
    pattern: /admin/eliminarActualizacion/
    defaults: {_controller: TheClickCmsAdminBundle:Default:eliminarActualizacion}

uploadFotoEmpresa:
    pattern: /admin/uploadFotoEmpresa
    defaults: {_controller: TheClickCmsAdminBundle:Default:uploadFotoEmpresa}

vistaUploadEmpresa2:
    pattern: /admin/vistaUploadEmpresa
    defaults: {_controller: TheClickCmsAdminBundle:Default:vistaUploadEmpresa}

eliminarArchivoActualizacion:
    pattern: /admin/eliminarArchivoActualizacion
    defaults: {_controller: TheClickCmsAdminBundle:Default:eliminarArchivoActualizacion}

eliminarFotoEmpresa:
    pattern: /admin/eliminarFotoEmpresa
    defaults: {_controller: TheClickCmsAdminBundle:Default:eliminarFotoEmpresa}