the_click_cmspaginas_homepage:
    pattern:  /home
    defaults: { _controller: TheClickCmspaginasBundle:Default:index }

vistaHistoria:
    pattern:  /home/vistaHistoria
    defaults: { _controller:  TheClickCmspaginasBundle:Default:vistaHistoria }

vistaContacto:
    pattern: /home/vistaContacto
    defaults: {_controller: TheClickCmspaginasBundle:Default:vistaContacto}

vistaAcceso:
    pattern: /home/vistaAcceso
    defaults: {_controller: TheClickCmspaginasBundle:Default:vistaAcceso}

recibeContacto:
    pattern: /home/recibeContacto
    defaults: {_controller: TheClickCmspaginasBundle:Default:recibeContacto}

nt:
    pattern: /home/noticias
    defaults: {_controller: TheClickCmspaginasBundle:Default:noticias}

servicio:
    path:      /home/servicio
    defaults:  { _controller: TheClickCmspaginasBundle:Default:servicio }

productos:
    pattern: /home/productos
    defaults: {_controller: TheClickCmspaginasBundle:Default:productos}

recibeFormularioAcceso:  
    pattern: /home/recibeFormularioAcceso
    defaults: {_controller: TheClickCmspaginasBundle:Default:recibeFormularioAcceso}

recibeformularioEditar:
    pattern: /home/recibeformularioEditar
    defaults: {_controller: TheClickCmspaginasBundle:Default:recibeformularioEditar}

cambioClave:
    pattern: /home/cambioClave
    defaults: {_controller: TheClickCmspaginasBundle:Default:cambioClave}

idioma:
    pattern: /home/idioma
    defaults: {_controller: TheClickCmspaginasBundle:Default:idioma}

vistaRegistrate:
    pattern: /home/vistaRegistrate
    defaults: {_controller: TheClickCmspaginasBundle:Default:vistaRegistrate}

registrate:
    pattern: /home/registrate
    defaults: {_controller: TheClickCmspaginasBundle:Default:registrate}