parameters:
#    the_click_cmspaginas.example.class: TheClickCms\paginasBundle\Example

services:
#    the_click_cmspaginas.example:
#        class: %the_click_cmspaginas.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
