parameters:
#    the_click_cms_idioma.example.class: TheClickCms\IdiomaBundle\Example

services:
#    the_click_cms_idioma.example:
#        class: %the_click_cms_idioma.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
